# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: swift
#xcode_project: travis.xcodeproj
#xcode_scheme: Handy
#xcode_sdk: iphonesimulator9.2
script:
- set -o pipefail && xcodebuild test -workspace Example/HandyNoti.xcworkspace -scheme HandyNoti-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
