# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.0
language: swift
script:
- set -o pipefail && xcodebuild test -workspace Example/HandyNoti.xcworkspace -scheme HandyNoti-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
