# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.0
language: swift
xcode_workspcae: Example/HandyNoti.xcworkspace # 项目文件相对于.travis.yml文件的路径

xcode_scheme: HandyNoti-Example #你需要集成测试的scheme
script:
#- set -o pipefail && xcodebuild test -workspace Example/HandyNoti.xcworkspace -scheme HandyNoti-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
