
osx_image: xcode8
language: objective-c

cache: cocoapods
podfile: Example/Podfile

env:
 global:
 - LANG=en_US.UTF-8
 - LC_ALL=en_US.UTF-8
 - XCODE_WORKSPACE=Example/HandyNoti.xcworkspace
 matrix:
 - SCHEME="HandyNoti-Example"

before_install:
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
 - pod repo update
 - pod install --project-directory=Example

script:
 - set -o pipefail
 - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
 - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
 - pod lib lint --no-clean

after_success:
 - sleep 5

# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode8.0
#language: swift
#xcode_workspcae: Example/HandyNoti.xcworkspace # 项目文件相对于.travis.yml文件的路径

#xcode_scheme: HandyNoti-Example #你需要集成测试的scheme
#script:
#- set -o pipefail && xcodebuild test -workspace Example/HandyNoti.xcworkspace -scheme HandyNoti-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
